[2025-02-06T10:36:56.355+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T10:36:56.366+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-06T10:36:51.763826+00:00 [queued]>
[2025-02-06T10:36:56.372+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-06T10:36:51.763826+00:00 [queued]>
[2025-02-06T10:36:56.372+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T10:36:56.382+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-02-06 10:36:51.763826+00:00
[2025-02-06T10:36:56.387+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5208) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-06T10:36:56.389+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'load_data', 'manual__2025-02-06T10:36:51.763826+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmpik644voj']
[2025-02-06T10:36:56.393+0000] {standard_task_runner.py:72} INFO - Started process 5210 to run task
[2025-02-06T10:36:56.393+0000] {standard_task_runner.py:105} INFO - Job 104: Subtask load_data
[2025-02-06T10:36:56.429+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-06T10:36:51.763826+00:00 [running]> on host b176106a6d6f
[2025-02-06T10:36:56.664+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-06T10:36:51.763826+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-06T10:36:51.763826+00:00'
[2025-02-06T10:36:56.665+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T10:36:56.676+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-02-06T10:36:58.589+0000] {dag_que_faire_a_paris.py:182} INFO - âœ… Loading completed successfully!
[2025-02-06T10:36:58.591+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-06T10:36:58.599+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T10:36:58.599+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=load_data, run_id=manual__2025-02-06T10:36:51.763826+00:00, execution_date=20250206T103651, start_date=20250206T103656, end_date=20250206T103658
[2025-02-06T10:36:58.658+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-06T10:36:58.666+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-06T10:36:58.670+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
