[2025-02-05T20:38:53.380+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T20:38:53.391+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-05T20:38:49.266465+00:00 [queued]>
[2025-02-05T20:38:53.396+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-05T20:38:49.266465+00:00 [queued]>
[2025-02-05T20:38:53.397+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T20:38:53.408+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-02-05 20:38:49.266465+00:00
[2025-02-05T20:38:53.412+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2713) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T20:38:53.414+0000] {standard_task_runner.py:72} INFO - Started process 2715 to run task
[2025-02-05T20:38:53.414+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'load_data', 'manual__2025-02-05T20:38:49.266465+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmp6w0dayrx']
[2025-02-05T20:38:53.415+0000] {standard_task_runner.py:105} INFO - Job 92: Subtask load_data
[2025-02-05T20:38:53.451+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-05T20:38:49.266465+00:00 [running]> on host b176106a6d6f
[2025-02-05T20:38:53.609+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T20:38:49.266465+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T20:38:49.266465+00:00'
[2025-02-05T20:38:53.610+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T20:38:53.622+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-02-05T20:38:55.010+0000] {dag_que_faire_a_paris.py:165} INFO - âœ… Loading completed successfully!
[2025-02-05T20:38:55.017+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-05T20:38:55.030+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T20:38:55.032+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=load_data, run_id=manual__2025-02-05T20:38:49.266465+00:00, execution_date=20250205T203849, start_date=20250205T203853, end_date=20250205T203855
[2025-02-05T20:38:55.075+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T20:38:55.087+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T20:38:55.091+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
