[2025-02-05T13:56:02.026+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T13:56:02.034+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-05T13:55:54.423054+00:00 [queued]>
[2025-02-05T13:56:02.039+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-05T13:55:54.423054+00:00 [queued]>
[2025-02-05T13:56:02.040+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T13:56:02.048+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-02-05 13:55:54.423054+00:00
[2025-02-05T13:56:02.052+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T13:56:02.053+0000] {standard_task_runner.py:72} INFO - Started process 97 to run task
[2025-02-05T13:56:02.053+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'load_data', 'manual__2025-02-05T13:55:54.423054+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmpf0pkap1k']
[2025-02-05T13:56:02.055+0000] {standard_task_runner.py:105} INFO - Job 73: Subtask load_data
[2025-02-05T13:56:02.080+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-05T13:55:54.423054+00:00 [running]> on host 878f1ba0d333
[2025-02-05T13:56:02.247+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T13:55:54.423054+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T13:55:54.423054+00:00'
[2025-02-05T13:56:02.249+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T13:56:02.264+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-02-05T13:56:03.475+0000] {dag_que_faire_a_paris.py:150} INFO - âœ… Loading completed successfully!
[2025-02-05T13:56:03.478+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-05T13:56:03.491+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T13:56:03.492+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=load_data, run_id=manual__2025-02-05T13:55:54.423054+00:00, execution_date=20250205T135554, start_date=20250205T135602, end_date=20250205T135603
[2025-02-05T13:56:03.512+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T13:56:03.521+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T13:56:03.524+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
