[2025-02-05T14:30:30.384+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T14:30:30.392+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.extract_data manual__2025-02-05T14:30:28.304645+00:00 [queued]>
[2025-02-05T14:30:30.398+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.extract_data manual__2025-02-05T14:30:28.304645+00:00 [queued]>
[2025-02-05T14:30:30.398+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T14:30:30.517+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-05 14:30:28.304645+00:00
[2025-02-05T14:30:30.521+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=86) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T14:30:30.523+0000] {standard_task_runner.py:72} INFO - Started process 88 to run task
[2025-02-05T14:30:30.522+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'extract_data', 'manual__2025-02-05T14:30:28.304645+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmpp_40_abf']
[2025-02-05T14:30:30.524+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask extract_data
[2025-02-05T14:30:30.550+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.extract_data manual__2025-02-05T14:30:28.304645+00:00 [running]> on host b176106a6d6f
[2025-02-05T14:30:30.594+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T14:30:28.304645+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T14:30:28.304645+00:00'
[2025-02-05T14:30:30.595+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T14:30:33.152+0000] {dag_que_faire_a_paris.py:40} INFO - âœ… Extraction completed successfully!
[2025-02-05T14:30:33.157+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-05T14:30:33.165+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T14:30:33.169+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=extract_data, run_id=manual__2025-02-05T14:30:28.304645+00:00, execution_date=20250205T143028, start_date=20250205T143030, end_date=20250205T143033
[2025-02-05T14:30:33.226+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T14:30:33.246+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-05T14:30:33.251+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
