[2025-02-06T09:21:05.300+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T09:21:05.310+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-06T09:21:00.620129+00:00 [queued]>
[2025-02-06T09:21:05.316+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-06T09:21:00.620129+00:00 [queued]>
[2025-02-06T09:21:05.316+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T09:21:05.326+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-02-06 09:21:00.620129+00:00
[2025-02-06T09:21:05.332+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4186) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-06T09:21:05.333+0000] {standard_task_runner.py:72} INFO - Started process 4188 to run task
[2025-02-06T09:21:05.333+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'load_data', 'manual__2025-02-06T09:21:00.620129+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmp5u608iat']
[2025-02-06T09:21:05.335+0000] {standard_task_runner.py:105} INFO - Job 101: Subtask load_data
[2025-02-06T09:21:05.364+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-06T09:21:00.620129+00:00 [running]> on host b176106a6d6f
[2025-02-06T09:21:05.529+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-06T09:21:00.620129+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-06T09:21:00.620129+00:00'
[2025-02-06T09:21:05.531+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T09:21:05.545+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-02-06T09:21:06.781+0000] {dag_que_faire_a_paris.py:182} INFO - âœ… Loading completed successfully!
[2025-02-06T09:21:06.784+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-06T09:21:06.796+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T09:21:06.797+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=load_data, run_id=manual__2025-02-06T09:21:00.620129+00:00, execution_date=20250206T092100, start_date=20250206T092105, end_date=20250206T092106
[2025-02-06T09:21:06.832+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-06T09:21:06.840+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
