[2025-02-05T20:47:15.986+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T20:47:15.996+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-05T20:47:11.145227+00:00 [queued]>
[2025-02-05T20:47:16.001+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-05T20:47:11.145227+00:00 [queued]>
[2025-02-05T20:47:16.001+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T20:47:16.010+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-02-05 20:47:11.145227+00:00
[2025-02-05T20:47:16.014+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2829) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T20:47:16.015+0000] {standard_task_runner.py:72} INFO - Started process 2838 to run task
[2025-02-05T20:47:16.015+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'load_data', 'manual__2025-02-05T20:47:11.145227+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmpipwpeehr']
[2025-02-05T20:47:16.017+0000] {standard_task_runner.py:105} INFO - Job 95: Subtask load_data
[2025-02-05T20:47:16.045+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-05T20:47:11.145227+00:00 [running]> on host b176106a6d6f
[2025-02-05T20:47:16.205+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T20:47:11.145227+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T20:47:11.145227+00:00'
[2025-02-05T20:47:16.206+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T20:47:16.223+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-02-05T20:47:17.603+0000] {dag_que_faire_a_paris.py:180} INFO - âœ… Loading completed successfully!
[2025-02-05T20:47:17.606+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-05T20:47:17.619+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T20:47:17.620+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=load_data, run_id=manual__2025-02-05T20:47:11.145227+00:00, execution_date=20250205T204711, start_date=20250205T204715, end_date=20250205T204717
[2025-02-05T20:47:17.676+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T20:47:17.699+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T20:47:17.704+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
